export interface ArkVoice {
    id: string
    name: string
    description: string
    gender: 'male' | 'female'
    language: string
    accent?: string
    tags: string[]
    previewUrl?: string
}

export const ARK_SYSTEM_VOICES: ArkVoice[] = [
    {
        id: 'zh_female_vv_uranus_bigtts',
        name: 'Vivi',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_xiaohe_uranus_bigtts',
        name: '小何',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_m191_uranus_bigtts',
        name: '云舟',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_taocheng_uranus_bigtts',
        name: '小天',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_liufei_uranus_bigtts',
        name: '刘飞',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_sophie_uranus_bigtts',
        name: '魅力苏菲',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_qingxinnvsheng_uranus_bigtts',
        name: '清新女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_cancan_uranus_bigtts',
        name: '知性灿灿',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_sajiaoxuemei_uranus_bigtts',
        name: '撒娇学妹',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_tianmeixiaoyuan_uranus_bigtts',
        name: '甜美小源',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_tianmeitaozi_uranus_bigtts',
        name: '甜美桃子',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_shuangkuaisisi_uranus_bigtts',
        name: '爽快思思',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_peiqi_uranus_bigtts',
        name: '佩奇猪',
        description: '视频配音',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_linjianvhai_uranus_bigtts',
        name: '邻家女孩',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_shaonianzixin_uranus_bigtts',
        name: '少年梓辛/Brayan',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_sunwukong_uranus_bigtts',
        name: '猴哥',
        description: '视频配音',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_yingyujiaoxue_uranus_bigtts',
        name: 'Tina老师',
        description: '教育场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_kefunvsheng_uranus_bigtts',
        name: '暖阳女声',
        description: '客服场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_xiaoxue_uranus_bigtts',
        name: '儿童绘本',
        description: '有声阅读',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_dayi_uranus_bigtts',
        name: '大壹',
        description: '视频配音',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_mizai_uranus_bigtts',
        name: '黑猫侦探社咪仔',
        description: '视频配音',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_jitangnv_uranus_bigtts',
        name: '鸡汤女',
        description: '视频配音',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_meilinvyou_uranus_bigtts',
        name: '魅力女友',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_liuchangnv_uranus_bigtts',
        name: '流畅女声',
        description: '视频配音',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_ruyayichen_uranus_bigtts',
        name: '儒雅逸辰',
        description: '视频配音',
        gender: 'male',
        language: 'English',
        tags: [],
    },
    {
        id: 'en_male_tim_uranus_bigtts',
        name: 'Tim',
        description: '多语种',
        gender: 'male',
        language: 'English',
        tags: [],
    },
    {
        id: 'en_female_dacey_uranus_bigtts',
        name: 'Dacey',
        description: '多语种',
        gender: 'female',
        language: 'English',
        tags: [],
    },
    {
        id: 'en_female_stokie_uranus_bigtts',
        name: 'Stokie',
        description: '多语种',
        gender: 'female',
        language: 'English',
        tags: [],
    },
    {
        id: 'zh_female_wenroumama_uranus_bigtts',
        name: '温柔妈妈',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_jieshuoxiaoming_uranus_bigtts',
        name: '解说小明',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_tvbnv_uranus_bigtts',
        name: 'TVB女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_yizhipiannan_uranus_bigtts',
        name: '译制片男',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_qiaopinv_uranus_bigtts',
        name: '俏皮女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_zhishuaiyingzi_uranus_bigtts',
        name: '直率英子',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_linjiananhai_uranus_bigtts',
        name: '邻家男孩',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_silang_uranus_bigtts',
        name: '四郎',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_ruyaqingnian_uranus_bigtts',
        name: '儒雅青年',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_qingcang_uranus_bigtts',
        name: '擎苍',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_xionger_uranus_bigtts',
        name: '熊二',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_yingtaowanzi_uranus_bigtts',
        name: '樱桃丸子',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_wennuanahu_uranus_bigtts',
        name: '温暖阿虎/Alvin',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_naiqimengwa_uranus_bigtts',
        name: '奶气萌娃',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_popo_uranus_bigtts',
        name: '婆婆',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_gaolengyujie_uranus_bigtts',
        name: '高冷御姐',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_aojiaobazong_uranus_bigtts',
        name: '傲娇霸总',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_lanyinmianbao_uranus_bigtts',
        name: '懒音绵宝',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_fanjuanqingnian_uranus_bigtts',
        name: '反卷青年',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_wenroushunv_uranus_bigtts',
        name: '温柔淑女',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_gufengshaoyu_uranus_bigtts',
        name: '古风少御',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_huolixiaoge_uranus_bigtts',
        name: '活力小哥',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_baqiqingshu_uranus_bigtts',
        name: '霸气青叔',
        description: '有声阅读',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_xuanyijieshuo_uranus_bigtts',
        name: '悬疑解说',
        description: '有声阅读',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_mengyatou_uranus_bigtts',
        name: '萌丫头/Cutey',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_tiexinnvsheng_uranus_bigtts',
        name: '贴心女声/Candy',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_jitangmei_uranus_bigtts',
        name: '鸡汤妹妹/Hope',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_cixingjieshuonan_uranus_bigtts',
        name: '磁性解说男声/Morgan',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_liangsangmengzai_uranus_bigtts',
        name: '亮嗓萌仔',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_kailangjiejie_uranus_bigtts',
        name: '开朗姐姐',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_gaolengchenwen_uranus_bigtts',
        name: '高冷沉稳',
        description: '通用场景',
        gender: 'male',
        language: 'English',
        tags: [],
    },
    {
        id: 'zh_male_shenyeboke_uranus_bigtts',
        name: '深夜播客',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_lubanqihao_uranus_bigtts',
        name: '鲁班七号',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_jiaochuannv_uranus_bigtts',
        name: '娇喘女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_linxiao_uranus_bigtts',
        name: '林潇',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_lingling_uranus_bigtts',
        name: '玲玲姐姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_chunribu_uranus_bigtts',
        name: '春日部姐姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_tangseng_uranus_bigtts',
        name: '唐僧',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_zhuangzhou_uranus_bigtts',
        name: '庄周',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_kailangdidi_uranus_bigtts',
        name: '开朗弟弟',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_zhubajie_uranus_bigtts',
        name: '猪八戒',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_ganmaodianyin_uranus_bigtts',
        name: '感冒电音姐姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_chanmeinv_uranus_bigtts',
        name: '谄媚女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_nvleishen_uranus_bigtts',
        name: '女雷神',
        description: '角色扮演',
        gender: 'female',
        language: 'English',
        tags: [],
    },
    {
        id: 'zh_female_qinqienv_uranus_bigtts',
        name: '亲切女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_kuailexiaodong_uranus_bigtts',
        name: '快乐小东',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_kailangxuezhang_uranus_bigtts',
        name: '开朗学长',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_youyoujunzi_uranus_bigtts',
        name: '悠悠君子',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_wenjingmaomao_uranus_bigtts',
        name: '文静毛毛',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_zhixingnv_uranus_bigtts',
        name: '知性女声',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_qingshuangnanda_uranus_bigtts',
        name: '清爽男大',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_yuanboxiaoshu_uranus_bigtts',
        name: '渊博小叔',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_yangguangqingnian_uranus_bigtts',
        name: '阳光青年',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_qingchezizi_uranus_bigtts',
        name: '清澈梓梓',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_tianmeiyueyue_uranus_bigtts',
        name: '甜美悦悦',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_xinlingjitang_uranus_bigtts',
        name: '心灵鸡汤',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_wenrouxiaoge_uranus_bigtts',
        name: '温柔小哥',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_roumeinvyou_uranus_bigtts',
        name: '柔美女友',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_dongfanghaoran_uranus_bigtts',
        name: '东方浩然',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_wenrouxiaoya_uranus_bigtts',
        name: '温柔小雅',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_tiancaitongsheng_uranus_bigtts',
        name: '天才童声',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_wuzetian_uranus_bigtts',
        name: '武则天',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_gujie_uranus_bigtts',
        name: '顾姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_guanggaojieshuo_uranus_bigtts',
        name: '广告解说',
        description: '通用场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_shaoergushi_uranus_bigtts',
        name: '少儿故事',
        description: '有声阅读',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_tiaopigongzhu_tob',
        name: '调皮公主',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_shuanglangshaonian_tob',
        name: '爽朗少年',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_tiancaitongzhuo_tob',
        name: '天才同桌',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_cancan_tob',
        name: '知性灿灿',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_aojiaonvyou_tob',
        name: '傲娇女友',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_bingjiaojiejie_tob',
        name: '病娇姐姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_chengshujiejie_tob',
        name: '成熟姐姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_keainvsheng_tob',
        name: '可爱女生',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_nuanxinxuejie_tob',
        name: '暖心学姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_tiexinnvyou_tob',
        name: '贴心女友',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_wenrouwenya_tob',
        name: '温柔文雅',
        description: '通用场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_wumeiyujie_tob',
        name: '妩媚御姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_xingganyujie_tob',
        name: '性感御姐',
        description: '角色扮演',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_aiqilingren_tob',
        name: '傲气凌人',
        description: '角色扮演',
        gender: 'male',
        language: 'English',
        tags: [],
    },
    {
        id: 'saturn_zh_male_aojiaogongzi_tob',
        name: '傲娇公子',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_aojiaojingying_tob',
        name: '傲娇精英',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_aomanshaoye_tob',
        name: '傲慢少爷',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_badaoshaoye_tob',
        name: '霸道少爷',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_bingjiaobailian_tob',
        name: '病娇白莲',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_bujiqingnian_tob',
        name: '不羁青年',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_chengshuzongcai_tob',
        name: '成熟总裁',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_cixingnansang_tob',
        name: '磁性男嗓',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_cujingnanyou_tob',
        name: '醋精男友',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_fengfashaonian_tob',
        name: '风发少年',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_fuheigongzi_tob',
        name: '腹黑公子',
        description: '角色扮演',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_qingyingduoduo_cs_tob',
        name: '轻盈朵朵',
        description: '客服场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_wenwanshanshan_cs_tob',
        name: '温婉珊珊',
        description: '客服场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_female_reqingaina_cs_tob',
        name: '热情艾娜',
        description: '客服场景',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'saturn_zh_male_qingxinmumu_cs_tob',
        name: '清新沐沐',
        description: '客服场景',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_vv_jupiter_bigtts',
        name: 'vivi',
        description: 'S2S-Omni',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_female_xiaohe_jupiter_bigtts',
        name: '小何',
        description: '',
        gender: 'female',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_yunzhou_jupiter_bigtts',
        name: '云舟',
        description: '',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    },
    {
        id: 'zh_male_xiaotian_jupiter_bigtts',
        name: '小天',
        description: '',
        gender: 'male',
        language: '中文-普通话',
        tags: [],
    }
]
