export interface MinimaxVoice {
    id: string
    name: string
    description: string
    gender: 'male' | 'female'
    language: string
    accent?: string
    tags: string[]
    previewUrl?: string
}

export const MINIMAX_SYSTEM_VOICES: MinimaxVoice[] = [
    {
        id: 'male-qn-qingse',
        name: '青涩青年',
        description: '充满朝气的男声，声线清爽，适合青春题材、校园故事等场景。',
        gender: 'male',
        language: '中文-普通话',
        tags: ['清爽', '校园', '青春'],
    },
    {
        id: 'male-qn-jingying',
        name: '精英青年',
        description: '干练成熟的男声，语调自信，适合职场解说、商业广告等。',
        gender: 'male',
        language: '中文-普通话',
        tags: ['成熟', '职场', '专业'],
    },
    {
        id: 'male-qn-badao',
        name: '霸道总裁',
        description: '低沉且充满磁性的男声，气场强大，适合现代言情、广播剧。',
        gender: 'male',
        language: '中文-普通话',
        tags: ['磁性', '低沉', '言情'],
    },
    {
        id: 'female-shaonv',
        name: '活力少女',
        description: '活泼开朗的女声，清脆甜美，适合二次元、轻松愉快的内容。',
        gender: 'female',
        language: '中文-普通话',
        tags: ['甜美', '活泼', '二次元'],
    },
    {
        id: 'female-yujie',
        name: '傲娇御姐',
        description: '气场全开的女声，声音成熟且富有魅力，适合大女主剧本或美妆解说。',
        gender: 'female',
        language: '中文-普通话',
        tags: ['成熟', '魅力', '御姐'],
    },
    {
        id: 'female-chengshu',
        name: '知性女性',
        description: '温婉大气的女声，富有知性美，适合情感电台、纪录片旁白。',
        gender: 'female',
        language: '中文-普通话',
        tags: ['知性', '温婉', '治愈'],
    },
    {
        id: 'Chinese (Mandarin)_News_Anchor',
        name: '新闻女声',
        description: '端庄大气的女声，明亮圆润，干练利落。风格客观理性，自带标准新闻现场感，适合严肃新闻、快讯播报。',
        gender: 'female',
        language: '中文-普通话',
        accent: '标准',
        tags: ['专业', '新闻', '端庄'],
    },
    {
        id: 'Chinese (Mandarin)_HK_Flight_Attendant',
        name: '港普空姐',
        description: '充满活力的女声，清脆明亮，快言快语。直爽真实，极具生活气息，适合都市广播剧或粤语播客。',
        gender: 'female',
        language: '中文-普通话',
        accent: '南方',
        tags: ['活力', '港普', '直爽'],
    },
    {
        id: 'Cantonese_ProfessionalHost（F)',
        name: '粤语女主持',
        description: '专业客观的粤语女声，吐字清晰，适合各类正式场合的粤语解说与新闻播报。',
        gender: 'female',
        language: '中文-粤语',
        accent: '粤语',
        tags: ['专业', '主持', '粤语'],
    },
    {
        id: 'Cantonese_PlayfulMan',
        name: '活泼粤语男',
        description: '轻松幽默的粤语男声，节奏轻快，适合综艺解说、搞笑视频。',
        gender: 'male',
        language: '中文-粤语',
        accent: '粤语',
        tags: ['轻松', '幽默', '粤语'],
    },
    {
        id: 'Patient Man',
        name: 'Patient Man (深情讲述者)',
        description: '专为情感类内容设计的成熟讲述者。声音低沉磁性，舒缓流畅。给人一种深情、治愈的感觉。',
        gender: 'male',
        language: '英文',
        accent: '英音',
        tags: ['深情', '治愈', '低沉'],
    },
    {
        id: 'English_Trustworthy_Man',
        name: 'Trustworthy Man',
        description: '值得信赖的英文男声，沉稳大气，非常适合商业广告或教育课件。',
        gender: 'male',
        language: '英文',
        accent: '美音',
        tags: ['专业', '沉稳', '商业'],
    },
    {
        id: 'English_Graceful_Lady',
        name: 'Graceful Lady',
        description: '优雅知性的英文女声，语调柔和，适合散文朗读、有声书。',
        gender: 'female',
        language: '英文',
        accent: '英音',
        tags: ['优雅', '知性', '温柔'],
    },
    {
        id: 'Japanese_IntellectualSenior',
        name: '高智学长 (日文)',
        description: '温润如玉的青年男声。清澈柔和，舒缓从容、充满诗意，透着历经世事的淡然。',
        gender: 'male',
        language: '日文',
        accent: '标准',
        tags: ['温润', '治愈', '清澈'],
    },
    {
        id: 'Japanese_GentleButler',
        name: '温柔执事 (日文)',
        description: '彬彬有礼的日文男声，语调轻柔，服务感十足，适合二次元管家角色。',
        gender: 'male',
        language: '日文',
        accent: '标准',
        tags: ['温柔', '礼貌', '二次元'],
    },
    {
        id: 'Japanese_DependableWoman',
        name: '知心姐姐 (日文)',
        description: '温柔体贴的日文女声，像知心大姐姐一样，适合ASMR或治愈系陪伴内容。',
        gender: 'female',
        language: '日文',
        accent: '标准',
        tags: ['陪伴', '治愈', '温柔'],
    },
    {
        id: 'Korean_SweetGirl',
        name: '甜美少女 (韩文)',
        description: '典型韩剧女主角声线，甜美可爱，情绪饱满，适合言情剧情配音。',
        gender: 'female',
        language: '韩文',
        accent: '标准',
        tags: ['甜美', '言情', '韩剧'],
    },
    {
        id: 'Korean_CheerfulBoyfriend',
        name: '阳光男友 (韩文)',
        description: '开朗阳光的韩文男声，像邻家大男孩，适合日常Vlog或轻松剧情。',
        gender: 'male',
        language: '韩文',
        accent: '标准',
        tags: ['阳光', '开朗', '日常'],
    },
    {
        id: 'tianxin_xiaoling',
        name: '甜心小玲',
        description: '极度甜美可爱的女童声，适合儿童绘本、动画片配音。',
        gender: 'female',
        language: '中文-普通话',
        tags: ['儿童', '甜美', '绘本'],
    },
    {
        id: 'cute_boy',
        name: '可爱男童',
        description: '天真无邪的男童声，充满童趣，适合少儿频道节目解说。',
        gender: 'male',
        language: '中文-普通话',
        tags: ['儿童', '童趣', '天真'],
    },
    {
        id: 'Chinese (Mandarin)_Warm_Bestie',
        name: '温暖闺蜜',
        description: '像好朋友一样的亲切女声，语调轻松自然，适合谈心类的播客。',
        gender: 'female',
        language: '中文-普通话',
        tags: ['亲切', '自然', '播客'],
    },
    {
        id: 'Chinese (Mandarin)_Humorous_Elder',
        name: '搞笑大爷',
        description: '风趣幽默的老年男声，带有生活气息，适合喜剧短片或地方特色内容。',
        gender: 'male',
        language: '中文-普通话',
        tags: ['幽默', '老年', '生活'],
    },
]
